title: Be-cGi - Capital Relacional
description: Be-cGi es una consultora especializada en aumentar el capital económico de las organizaciones a través del capital relacional. Grandes organizaciones en América.
logo: /assets/images/logo.jpeg
favicon: /assets/images/logo.jpeg
social_links:
  linkedin: becgi-consulting
  twitter: BecGiConsulting
github_username: GalacticaSystem
repository: GalacticaSystem/becgi-web
baseurl: "/becgi-web" # Necesario para GitHub Pages en repo que no es username.github.io

# Collections configuration
collections:
  projects:
    output: true
    permalink: /portfolio/:path/

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Defaults for posts and projects
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: default